name: HackMoc Blog
description: HackMoc Blog
url: http://hackmoc.org/
markdown: redcarpet
pygments: true

authors:
    herberth:
        display_name: Herberth Amaral
        gravatar: e71567f551826c783efd8f91a577b43c
        email: herberthamaral@gmail.com
        web: http://herberthamaral.com/
        twitter: herberthamaral 
        github: herberthamaral
    mbodock:
        display_name: Marcus Bodock
        gravatar: db2387f968e2061655fbeac3c97a4f32
        email: mbodock@gmail.com
        web: http://bodock.com.br/
        twitter: mbodock
        github: mbodock
    myhro:
        display_name: Tiago Ilieve
        gravatar: 958aa7cf76a1ee7a853d1719be4ebb38
        email: tiago.myhro@gmail.com
        web: https://blog.myhro.info/
        twitter: myhro
        github: myhro
    esteban:
        display_name: Gustavo Pinho
        gravatar: 6d49e0ea3a4b28fd39590b2ce17418fb 
        email: gustavopinho@gustavopinho.com
        web: http://gustavopinho.com
        twitter: JG_Pinho 
        github: gustavopinho
