name: HackMoc Blog
markdown: redcarpet
pygments: true

authors:
    herberth:
        display_name: Herberth Amaral
        gravatar: e71567f551826c783efd8f91a577b43c
        email: herberthamaral@gmail.com
        web: http://herberthamaral.com/
        twitter: herberthamaral 
        github: herberthamaral
    mbodock:
        display_name: Marcus Bodock
        gravatar: db2387f968e2061655fbeac3c97a4f32
        email: mbodock@gmail.com
        web: http://bodock.com.br/
        twitter: mbodock
        github: mbodock
